import type { MediaManager } from '../media/mediaManager';
import { PRESETS } from '../state/presets';
import type { Store } from '../state/store';
import type { FaceId } from '../state/types';
import { formatAspect } from '../util/aspect';
const labels:Record<FaceId,string>={front:'正面',left:'左側面',right:'右側面',floor:'床面',ceiling:'天井面'}; let sourceSequence=0;
function el<K extends keyof HTMLElementTagNameMap>(tag:K,attrs:Record<string,string>={}){const n=document.createElement(tag);for(const[k,v]of Object.entries(attrs))k==='class'?n.className=v:n.setAttribute(k,v);return n;}
export function createPanel(host:HTMLElement,store:Store,media:MediaManager){
 host.innerHTML='<div class="row controls"></div><div class="row params"></div><div id="aspect-info"></div>';const controls=host.querySelector('.controls')!,params=host.querySelector('.params')!;
 const mode=el('select');mode.innerHTML='<option value="separate">壁面 個別</option><option value="span">壁面 連続</option>';mode.onchange=()=>store.dispatch({type:'mode/set',mode:mode.value as 'separate'|'span'});controls.append(mode);const files=el('div',{class:'file-slots'});controls.append(files);
 const play=el('button');play.onclick=()=>store.dispatch({type:'playback/toggle'});controls.append(play);const restart=el('button',{class:'secondary'});restart.textContent='⏮ 先頭へ';restart.onclick=()=>store.dispatch({type:'playback/restart'});controls.append(restart);const seek=el('input',{type:'range',min:'0',max:'1000',value:'0',class:'seek'});seek.oninput=()=>{const m=media.getMaster(store.getState());if(m?.duration)store.dispatch({type:'playback/seek',time:+seek.value/1000*m.duration});};controls.append(seek);
 for(const[key,label,min,max]of[['orbit','視点','-40','40'],['pitch','高さ','0','90'],['dist','距離','60','140']]as const){const w=el('label');w.textContent=label;w.dataset.key=key;const i=el('input',{type:'range',min,max});i.oninput=()=>store.dispatch({type:'view/patch',patch:{[key]:+i.value}});w.append(i);controls.append(w);}
 const people=el('label');people.innerHTML='<input type="checkbox"> 人物表示';(people.firstElementChild as HTMLInputElement).onchange=e=>store.dispatch({type:'people/toggle',show:(e.target as HTMLInputElement).checked});controls.append(people);const mute=el('label');mute.innerHTML='<input type="checkbox"> ミュート';(mute.firstElementChild as HTMLInputElement).onchange=e=>store.dispatch({type:'playback/mute',muted:(e.target as HTMLInputElement).checked});controls.append(mute);
 const preset=el('select');preset.innerHTML='<option value="aquarium">3面</option><option value="u">コの字</option><option value="l">L字(正面+右)</option><option value="box">ボックス(5面)</option><option value="custom">カスタム</option>';preset.onchange=()=>{if(preset.value!=='custom')store.dispatch({type:'preset/apply',name:preset.value as keyof typeof PRESETS});};params.append('プリセット ',preset);const nums={}as Record<'W'|'H'|'D',HTMLInputElement>;
 for(const[key,label,step]of[['W','幅W(mm)','1'],['H','高さH(mm)','1'],['D','奥行D(mm)','0.1']]as const){const w=el('label');w.textContent=label;const i=el('input',{type:'number',min:'100',step});i.oninput=()=>store.dispatch({type:'params/patch',patch:{[key]:Math.max(100,+i.value||100)}});nums[key]=i;w.append(i);params.append(w);}const faceInputs={}as Record<FaceId,HTMLInputElement>;
 for(const face of['left','right','floor','ceiling']as FaceId[]){const w=el('label'),i=el('input',{type:'checkbox'});i.onchange=()=>store.dispatch({type:'params/patch',patch:{faces:{[face]:i.checked}}});faceInputs[face]=i;w.append(i,labels[face]);params.append(w);}
 function addFile(face:FaceId|'span'){const l=el('label',{class:'file-button'});l.textContent=face==='span'?'連続動画':labels[face];const i=el('input',{type:'file',accept:'video/*'});i.onchange=()=>{const f=i.files?.[0];if(!f)return;const source={id:`src-${++sourceSequence}`,kind:'file' as const,url:URL.createObjectURL(f),name:f.name};store.dispatch({type:'source/add',source});store.dispatch(face==='span'?{type:'assign/span',sourceId:source.id}:{type:'assign/face',face,sourceId:source.id});};l.append(i);files.append(l);}
 function render(state=store.getState()){mode.value=state.mode;play.textContent=state.playback.playing?'⏸ 停止':'▶ 再生';preset.value=state.preset;for(const k of['W','H','D']as const)nums[k].value=String(state.params[k]);for(const f of['left','right','floor','ceiling']as FaceId[])faceInputs[f].checked=state.params.faces[f];(people.firstElementChild as HTMLInputElement).checked=state.showPeople;(mute.firstElementChild as HTMLInputElement).checked=state.playback.muted;for(const k of['orbit','pitch','dist']as const)(controls.querySelector(`[data-key="${k}"] input`)as HTMLInputElement).value=String(state.view[k]);files.innerHTML='';if(state.mode==='span')addFile('span');else{addFile('front');if(state.params.faces.left)addFile('left');if(state.params.faces.right)addFile('right');}if(state.params.faces.floor)addFile('floor');if(state.params.faces.ceiling)addFile('ceiling');const p=state.params,parts=[`正面 ${Math.round(p.W)}×${Math.round(p.H)} → ${formatAspect(p.W,p.H)}`];if(p.faces.left)parts.push(`左 ${formatAspect(p.D,p.H)}`);if(p.faces.right)parts.push(`右 ${formatAspect(p.D,p.H)}`);if(p.faces.floor)parts.push(`床 ${formatAspect(p.W,p.D)}`);if(p.faces.ceiling)parts.push(`天井 ${formatAspect(p.W,p.D)}`);if(state.mode==='span'){const w=(p.faces.left?p.D:0)+p.W+(p.faces.right?p.D:0);parts.push(`連続ストリップ ${Math.round(w)}×${Math.round(p.H)} → ${formatAspect(w,p.H)}`);}(host.querySelector('#aspect-info')as HTMLElement).textContent=parts.join(' ｜ ');}
 render();const unsub=store.subscribe(render);let frame=0;const tick=()=>{const m=media.getMaster(store.getState());if(m?.duration&&document.activeElement!==seek)seek.value=String(m.currentTime/m.duration*1000);frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>{unsub();cancelAnimationFrame(frame);host.innerHTML='';};}
