import type { MediaManager } from '../media/mediaManager';
import type { Store } from '../state/store';
import type { FaceId } from '../state/types';
import { createPresentationMode } from '../ui/presentation';
let sourceSequence=0;
function el<K extends keyof HTMLElementTagNameMap>(tag:K,attrs:Record<string,string>={}){const n=document.createElement(tag);for(const[k,v]of Object.entries(attrs))k==='class'?n.className=v:n.setAttribute(k,v);return n;}
export function createPanel(host:HTMLElement,store:Store,media:MediaManager){
 host.innerHTML='<div class="row controls"></div><div id="aspect-info">正面 6.0×2.7m (20:9) ｜ 側面 4.19×2.7m (14:9) ｜ 床 6.0×4.19m ｜ 連続 34:9</div>';const controls=host.querySelector('.controls')!;
 const mode=el('select');mode.innerHTML='<option value="separate">壁面個別</option><option value="span">壁面連続(34:9を1本)</option>';mode.onchange=()=>store.dispatch({type:'mode/set',mode:mode.value as 'separate'|'span'});controls.append(mode);const files=el('div',{class:'file-slots'});controls.append(files);
 const play=el('button');play.onclick=()=>store.dispatch({type:'playback/toggle'});controls.append(play);const restart=el('button',{class:'secondary'});restart.textContent='⏮ 先頭へ';restart.onclick=()=>store.dispatch({type:'playback/restart'});controls.append(restart);const seek=el('input',{type:'range',min:'0',max:'1000',value:'0',class:'seek'});seek.oninput=()=>{const m=media.getMaster(store.getState());if(m?.duration)store.dispatch({type:'playback/seek',time:+seek.value/1000*m.duration});};controls.append(seek);
 const mute=el('label');mute.innerHTML='<input type="checkbox"> ミュート';(mute.firstElementChild as HTMLInputElement).onchange=e=>store.dispatch({type:'playback/mute',muted:(e.target as HTMLInputElement).checked});controls.append(mute);const people=el('label');people.innerHTML='<input type="checkbox"> 人物表示';(people.firstElementChild as HTMLInputElement).onchange=e=>store.dispatch({type:'people/toggle',show:(e.target as HTMLInputElement).checked});controls.append(people);
 for(const[key,label,min,max]of[['orbit','視点','-40','40'],['pitch','高さ','0','90'],['dist','距離','60','140']]as const){const w=el('label');w.textContent=label;w.dataset.key=key;const i=el('input',{type:'range',min,max});i.oninput=()=>store.dispatch({type:'view/patch',patch:{[key]:+i.value}});w.append(i);controls.append(w);}
 const presentation=createPresentationMode(),pres=el('button',{class:'secondary'});pres.textContent='🖥 全画面';pres.title='全画面プレゼンモード(Esc/Hで解除)';pres.onclick=()=>presentation.enter();controls.append(pres);
 function addFile(target:FaceId|'span',label:string){const l=el('label',{class:'file-button'});l.textContent=label;const i=el('input',{type:'file',accept:'video/*'});i.onchange=()=>{const f=i.files?.[0];if(!f)return;const source={id:`src-${++sourceSequence}`,kind:'file' as const,url:URL.createObjectURL(f),name:f.name};store.dispatch({type:'source/add',source});store.dispatch(target==='span'?{type:'assign/span',sourceId:source.id}:{type:'assign/face',face:target,sourceId:source.id});};l.append(i);files.append(l);}
 function render(state=store.getState()){mode.value=state.mode;play.textContent=state.playback.playing?'⏸ 停止':'▶ 再生';(mute.firstElementChild as HTMLInputElement).checked=state.playback.muted;(people.firstElementChild as HTMLInputElement).checked=state.showPeople;for(const k of['orbit','pitch','dist']as const)(controls.querySelector(`[data-key="${k}"] input`)as HTMLInputElement).value=String(state.view[k]);files.innerHTML='';if(state.mode==='span')addFile('span','壁面 34:9');else{addFile('front','正面 20:9');addFile('right','側面 14:9');}addFile('floor','床面');}
 render();const unsub=store.subscribe(render);let frame=0;const tick=()=>{const m=media.getMaster(store.getState());if(m?.duration&&document.activeElement!==seek)seek.value=String(m.currentTime/m.duration*1000);frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>{unsub();cancelAnimationFrame(frame);presentation.dispose();host.innerHTML='';};}
